import {
  Brain,
  ShieldAlert,
  TriangleAlert,
  CheckCircle2,
} from "lucide-react";

import Card from "@/components/ui/Card";

export default function AIInsights() {
  return (
    <Card className="p-6">
      <div className="mb-6 flex items-center gap-3">
        <div className="rounded-xl bg-violet-500/15 p-3 text-violet-400">
          <Brain size={24} />
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white">
            AI Security Insights
          </h2>

          <p className="text-sm text-slate-400">
            Generated by the Aegis AI Engine
          </p>
        </div>
      </div>

      <div className="space-y-4">

        <div className="rounded-xl border border-red-500/20 bg-red-500/10 p-4">
          <div className="mb-2 flex items-center gap-2 text-red-400">
            <ShieldAlert size={18} />
            <span className="font-semibold">
              Brute Force Campaign Detected
            </span>
          </div>

          <p className="text-sm text-slate-300">
            Multiple failed login attempts detected across exposed SSH
            endpoints.
          </p>
        </div>

        <div className="rounded-xl border border-yellow-500/20 bg-yellow-500/10 p-4">
          <div className="mb-2 flex items-center gap-2 text-yellow-400">
            <TriangleAlert size={18} />
            <span className="font-semibold">
              Risk Score
            </span>
          </div>

          <p className="text-3xl font-bold text-white">
            92%
          </p>

          <p className="mt-1 text-sm text-slate-300">
            High likelihood of credential attack.
          </p>
        </div>

        <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-4">
          <div className="mb-2 flex items-center gap-2 text-emerald-400">
            <CheckCircle2 size={18} />
            <span className="font-semibold">
              Recommended Action
            </span>
          </div>

          <ul className="space-y-2 text-sm text-slate-300">
            <li>• Block suspicious IP addresses</li>
            <li>• Enable MFA enforcement</li>
            <li>• Review authentication logs</li>
            <li>• Increase firewall monitoring</li>
          </ul>
        </div>

      </div>
    </Card>
  );
}